#capture time in tick
captureTime: 200
#scan delay in tick
scanDelay: 600
#effects clear delay in tick
effectsClearDelay: 200
#capture delay when entering in tick
captureEnteringDelay: 600
#escape delay when entering in tick
escapeEnteringDelay: 600
#default ranked money
rankedMoney: 1000
#default preparation time in seconds
preparationTime: 120